### ISSUE TITLE
Releasing v5 [TypeScript] Umbrella

### ISSUE THREAD

**Issue by JedWatson** [JedWatson/react-select#4559]
As originally discussed in #4142 we've rewritten react-select in TypeScript (🙌  **huge** props to @Methuselah96 for the heavy lifting here!)

This issue is to track the work involved in merging the TypeScript conversion (#4489), and getting a new major version (v5) released.

## Steps

- [x] Disable the website auto-publish on updates to master @bladey 
- [x] Merge #4489 @JedWatson 
  - [x] Fix `__isNew__` handling
  - [x] Merge https://github.com/JedWatson/react-select/pull/4702
- [x] Cleanup tasks (because we'll be bumping a major version)
  - [x] Switch to CSS Grid over `react-autosize-input` @ebonow PR https://github.com/JedWatson/react-select/pull/4625
  - [x] Update some styling and CSS decisions (including closing out #4720) @seancurtis
- [x] Update the website to use magical types @gwyneplaine in a subsequent PR
  - [x] look at what we can do to reduce the anticipated bundle size increase @mitchellhamilton 
- [x] Write the changelog and upgrade notes #4762 @Methuselah96 
  - [ ] Add a banner to the website
  - [ ] Call out updated Browser Support (Evergreen, officially not IE11)
- [ ] Release version 5 🎉

**Comment by Bosch-Eli-Black** [comment]
Any chance of publishing a beta build to NPM? 🙂

**Comment by ebonow** [comment]
Everyone, please note that this major release will be a complete rewrite so we officially halted PR's until release so we can focus on addressing on breaking changes and documentation. It is absolutely inexcusable that so many PR's have not been addressed but also know that quite a bit focus around Menu positioning, scrolling and sizing behavior are being looked at holistically and may be resolved in batch as we continue to experiment with Popper as a solution.

**Comment by Methuselah96** [comment]
We've released a `5.0.0-beta.0`.

**Comment by nicoburns** [comment]
This new update looks great (especially the TypeScript support). However dropping IE11 support unfortunately makes it a non-starter for us. I was wondering whether that decision could be reconsidered. I see that the main reason for dropping IE11 support seems to be lack of support for CSS grid, but IE11 does partially support CSS grid so I am wondering if it would be possible to get the auto-sizing grid hack to work with it.

@ebonow Did you attempt to get the grid hack to work with IE11? Is there a specific reason why it won't work?

**Comment by yournatalita** [comment]
Is there a reason you got rid of `makeAsyncSelect` or other functions like this? 

 I found them useful for those who has a lot of custom logic or customization and wants to keep it in one component without copy-pasting, but still wants to separate Async and Common to different components for export and provide ability to have non-async and async select that had been customized in one place.

I might assume it would be handful to have it in v5 too. 

-----

If it is not a thing for v5, how you would recommend to fix this issue? (Sorry if it is a noob question as I am a bit lost without docs)

Should we use not a default export  `StateManagedSelect` but a `Select` itself and customize data that passed to hooks based on our custom props? Or is there a better and easier way to do it?

**Comment by luxalpa** [comment]
@nicoburns 
I don't think it's worth it to invest into IE11 compatibility at this point as even Microsoft is no longer supporting it in their own apps and it's going to reach end of life quite soon:

> On August 17, 2020, Microsoft published a timeline indicating that the Microsoft Teams product would stop supporting Internet Explorer 11 on November 30, 2020, and Microsoft 365 products will end Internet Explorer 11 support on August 17, 2021.[9] In May 2021, Microsoft announced that support for Internet Explorer 11 on editions of Windows 10 that are not in the Long-Term Servicing Channel (LTSC) will end on June 15, 2022.[10] Internet Explorer 11 will not be supported on any editions of Windows 11.[11]

**Comment by hansfpc** [comment]
> This new update looks great (especially the TypeScript support). However dropping IE11 support unfortunately makes it a non-starter for us. I was wondering whether that decision could be reconsidered. I see that the main reason for dropping IE11 support seems to be lack of support for CSS grid, but IE11 does partially support CSS grid so I am wondering if it would be possible to get the auto-sizing grid hack to work with it.
> 
> @ebonow Did you attempt to get the grid hack to work with IE11? Is there a specific reason why it won't work?

I think the world has to let IE die. 
IE and "Progress" cannot be in the same phrase 😿  
I  have decided that I will never support IE in any piece of software I'll build

**Comment by Methuselah96** [comment]
[5.0](https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0) has been released!

**Comment by Bosch-Eli-Black** [comment]
What needs to be done to update the documentation at https://www.npmjs.com/package/react-select ? It still references the old v2 to v3 upgrade guide, etc. 🙂

**Comment by Rall3n** [comment]
Hello @Bosch-Eli-Black,

thanks for bringing this discrepancy to our attention. Seems like the packages `README.md` was forgotten during the preparations for the release.

**Comment by Bosch-Eli-Black** [comment]
@Rall3n Np! 🙂
